if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install(version = "3.18")

BiocManager::install(c("GEOquery","DESeq2","ggplot2", "dplyr", "gplots", "pheatmap", "EnhancedVolcano", "EDASeq", "biomaRt", "tibble", "openxlsx", "clusterProfiler"))

library(GEOquery)
library(DESeq2)
library(ggplot2)
library(dplyr)
library(gplots)
library(pheatmap)
library(EnhancedVolcano)
library(EDASeq)
library(biomaRt)
library(tibble)
library(openxlsx)
library(clusterProfiler)
